package exceptions;

public class Main {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		String s = null;
//int num1 = 100, num2 = 0;
//try {
//	int c = num1/num2;
//	System.out.println(c);
//}catch(ArithmeticException e) {
//	System.out.println(e);
//}
//System.out.println("Arithmetic excpetion");
//	}
//		System.out.println(s.length());

		addition a = (b,c)->(b+c);
		System.out.println(a.adds(2, 2));
	}
}
